impact_user:
    resource: "@ImpactUserBundle/Controller/"
    type:     annotation
    prefix:   /

impact_program:
    resource: "@ImpactProgramBundle/Controller/"
    type:     annotation
    prefix:   /

